language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t rmanish/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rmanish/react-test npm run test

after_success:
  - docker build -t rmanish/multi-client ./client
  - docker build -t rmanish/multi-nginx ./nginx
  - docker build -t rmanish/multi-server ./server
  - docker build -t rmanish/multi-worker ./worker
  # login into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push rmanish/multi-client
  - docker push rmanish/multi-nginx
  - docker push rmanish/multi-server
  - docker push rmanish/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-687997792686"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
